Support for discrete actions.
google-research/batch-ppo pull request #26
Opened 2018-01-23 18:39 UTC by blazej0

2018-01-25 15:04 UTC, danijar commented
Thanks, Błażej! Would you mind adding a test along the lines of the existing `TestPPO.test_cheetah_no_crash` for the cart pole environment?

2018-01-26 13:54 UTC, danijar requested changes
Thanks a lot for the PR. The code looks good, just a few syntax details to be consistent with the existing code (and Google's Python code style).

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +    action_space: Value of environment's action_space.
Action space of the environment.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/configs.py
> +
Insert empty line.

2018-01-26 13:54 UTC, danijar commented on agents/algorithms/ppo/ppo.py
> -          tf.reduce_all(tf.equal(network.policy.mean(), old_policy.mean())),
I think you can just remove this check. In the future, it should probably be checked in a unit test instead.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +  """Independent feed forward networks for policy and value.
Add empty line here, and before `Args:` and `Returns:`.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +    state: Batch of initial recurrent states.
Batch of **unused** initial states.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/configs.py
> +  return locals()
Missing newline at the end of the file.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +
Can you remove these empty lines, please?

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +    action_space: Value of environment's action_space.
Action space of the environment.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +  assert isinstance(action_space, gym.spaces.Discrete), "Expecting discrete actions"
We use single quotes for strings and have dots at the end of error messages by convention.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +  assert isinstance(action_space, gym.spaces.Box), "Expecting continuous actions"
Same as above.

2018-01-26 13:54 UTC, danijar commented on agents/scripts/networks.py
> +  action_size = action_space.shape[0]
Please add before this line:

```python
assert len(action_space.shape) == 1, 'Network only supports vector-shaped actions.'
```

2018-01-26 21:06 UTC, blazej0 commented
I signed it!

2018-01-26 21:08 UTC, blazej0 commented on agents/algorithms/ppo/ppo.py
> -          tf.reduce_all(tf.equal(network.policy.mean(), old_policy.mean())),
Done.

2018-01-26 21:19 UTC, blazej0 commented on agents/scripts/networks.py
> +  action_size = action_space.shape[0]
I assume it also applies to the feed_forward_gaussian?

2018-01-27 17:35 UTC, danijar requested changes
Thanks for the update. There are two linter errors left. We can merge this after you fixed them. You can also run the linter locally, the command is in the readme.

I'd make the changes myself but I can't add them to the PR as far as I know, and to import commits into Google, every commit should be clean.

2018-01-27 17:35 UTC, danijar commented on agents/scripts/configs.py
> +  return locals()
Now it's one line too much. There should be no empty line, but a newline character at the end of the last line (otherwise it's not a valid file on Unix). Github also shows a red warning if the last newline is missing.

2018-01-27 17:35 UTC, danijar commented on agents/scripts/networks.py
> +        x = tf.contrib.layers.fully_connected(x, size, tf.nn.relu)
Removed two spaces of indent.

2018-01-30 10:01 UTC, blazej0 commented
I signed it!

2018-01-30 10:22 UTC, danijar approved these changes

2018-01-30 10:33 UTC, merged